name: NusaTempFly
main: id.nusatempfly.Plugin
version: 1.0-SNAPSHOT
api-version: 1.20
description: Temporary flight plugin with time boosters
softdepend: [PlaceholderAPI, WorldGuard]
author: NusaDev

commands:
  fly:
    description: Main command for NusaTempFly plugin
    usage: /<command> [subcommand] [args]
    aliases: [tempfly, tf, tfly]
  
permissions:
  nusatempfly.admin:
    description: Access to all admin commands
    default: op
  nusatempfly.use:
    description: Allows using temporary flight
    default: true
  nusatempfly.booster:
    description: Gives time bonus when purchasing flight time
    default: false
  nusatempfly.bypass.region:
    description: Allows bypassing region flight restrictions
    default: op
  nusatempfly.bypass.timelimit:
    description: Allows flying without consuming flight time
    default: op
  nusatempfly.bypass.damage:
    description: Prevents flight from being disabled when taking damage
    default: op